spring.application.name=gmr-api
#server.servlet.context-path=/gmr
socketio.port=9092
socketio.hostname=localhost
# 100 * 1024 * 1024 - 100MB
socketio.max.frame.payload.length=104857600 
socketio.max.frame.payload.length=104857600

